(down)

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -530,51 +530,51 @@ jobs:
                     sleep 10
                   done
 
-            - name: Update Auth0 callbacks
-              env:
-                  AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
-                  CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
-                  CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
-                  SPA_CLIENT_ID: ${{ secrets.AUTH0_SPA_CLIENT_ID }}
-              run: |
-                  # Obtener el token de acceso de Auth0
-                  RESPONSE=$(curl --silent --request POST \
-                                  --url "https://$AUTH0_DOMAIN/oauth/token" \
-                                  --header 'content-type: application/json' \
-                                  --data "{\"client_id\":\"$CLIENT_ID\",\"client_secret\":\"$CLIENT_SECRET\",\"audience\":\"https://$AUTH0_DOMAIN/api/v2/\",\"grant_type\":\"client_credentials\"}")
+            # - name: Update Auth0 callbacks
+            #   env:
+            #       AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
+            #       CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
+            #       CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
+            #       SPA_CLIENT_ID: ${{ secrets.AUTH0_SPA_CLIENT_ID }}
+            #   run: |
+            #       # Obtener el token de acceso de Auth0
+            #       RESPONSE=$(curl --silent --request POST \
+            #                       --url "https://$AUTH0_DOMAIN/oauth/token" \
+            #                       --header 'content-type: application/json' \
+            #                       --data "{\"client_id\":\"$CLIENT_ID\",\"client_secret\":\"$CLIENT_SECRET\",\"audience\":\"https://$AUTH0_DOMAIN/api/v2/\",\"grant_type\":\"client_credentials\"}")
 
-                  # Verificar errores en la solicitud cURL
-                  if [ $? -ne 0 ]; then
-                    echo "Failed to obtain Access Token."
-                    exit 1
-                  fi
+            #       # Verificar errores en la solicitud cURL
+            #       if [ $? -ne 0 ]; then
+            #         echo "Failed to obtain Access Token."
+            #         exit 1
+            #       fi
 
-                  # Extraer Access Token de la respuesta JSON
-                  ACCESS_TOKEN=$(echo "$RESPONSE" | jq -r '.access_token')
+            #       # Extraer Access Token de la respuesta JSON
+            #       ACCESS_TOKEN=$(echo "$RESPONSE" | jq -r '.access_token')
 
-                  # Verificar si Access Token está vacío
-                  if [ -z "$ACCESS_TOKEN" ]; then
-                    echo "Failed to extract Access Token from the response."
-                    exit 1
-                  fi
+            #       # Verificar si Access Token está vacío
+            #       if [ -z "$ACCESS_TOKEN" ]; then
+            #         echo "Failed to extract Access Token from the response."
+            #         exit 1
+            #       fi
 
-                  FRONTEND_SERVICE_IP=$(kubectl get svc frontend-service -n argocd -o=jsonpath='{.status.loadBalancer.ingress[0].ip}')
+            #       FRONTEND_SERVICE_IP=$(kubectl get svc frontend-service -n argocd -o=jsonpath='{.status.loadBalancer.ingress[0].ip}')
 
-                  NEW_CALLBACK_URL="http://$FRONTEND_SERVICE_IP"
-                  NEW_CALLBACK_URL_HTTPS="https://frontend.leagueoftoken.online"
-                  NEW_CALLBACK_URL_HTTP="http://frontend.leagueoftoken.online"
+            #       NEW_CALLBACK_URL="http://$FRONTEND_SERVICE_IP"
+            #       NEW_CALLBACK_URL_HTTPS="https://frontend.leagueoftoken.online"
+            #       NEW_CALLBACK_URL_HTTP="http://frontend.leagueoftoken.online"
 
-                  # Actualizar la configuración del cliente SPA en Auth0
-                  curl --request PATCH \
-                    --url "https://$AUTH0_DOMAIN/api/v2/clients/$SPA_CLIENT_ID" \
-                    --header "authorization: Bearer $ACCESS_TOKEN" \
-                    --header 'content-type: application/json' \
-                    --data '{
-                      "callbacks": ["http://localhost:5173", "http://127.0.0.1:5173", "'"$NEW_CALLBACK_URL_HTTPS"'", "'"$NEW_CALLBACK_URL_HTTP"'", "'"$NEW_CALLBACK_URL"'"],
-                      "allowed_logout_urls": ["http://localhost:5173", "http://127.0.0.1:5173", "'"$NEW_CALLBACK_URL_HTTPS"'", "'"$NEW_CALLBACK_URL_HTTP"'", "'"$NEW_CALLBACK_URL"'"],
-                      "web_origins": ["http://localhost:5173", "http://127.0.0.1:5173", "'"$NEW_CALLBACK_URL_HTTPS"'", "'"$NEW_CALLBACK_URL_HTTP"'", "'"$NEW_CALLBACK_URL"'"],
-                    }' \
-                    > /dev/null 2>&1
+            #       # Actualizar la configuración del cliente SPA en Auth0
+            #       curl --request PATCH \
+            #         --url "https://$AUTH0_DOMAIN/api/v2/clients/$SPA_CLIENT_ID" \
+            #         --header "authorization: Bearer $ACCESS_TOKEN" \
+            #         --header 'content-type: application/json' \
+            #         --data '{
+            #           "callbacks": ["http://localhost:5173", "http://127.0.0.1:5173", "'"$NEW_CALLBACK_URL_HTTPS"'", "'"$NEW_CALLBACK_URL_HTTP"'", "'"$NEW_CALLBACK_URL"'"],
+            #           "allowed_logout_urls": ["http://localhost:5173", "http://127.0.0.1:5173", "'"$NEW_CALLBACK_URL_HTTPS"'", "'"$NEW_CALLBACK_URL_HTTP"'", "'"$NEW_CALLBACK_URL"'"],
+            #           "web_origins": ["http://localhost:5173", "http://127.0.0.1:5173", "'"$NEW_CALLBACK_URL_HTTPS"'", "'"$NEW_CALLBACK_URL_HTTP"'", "'"$NEW_CALLBACK_URL"'"],
+            #         }' \
+            #         > /dev/null 2>&1
 
             - name: Update Cloudflare DNS
               env:
