(up)

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -200,13 +200,17 @@ jobs:
                     rm credentials.json
                   fi
 
-            # TODO: Crear API token secret de Cloudflare
-            # - name: Create Cloudflare API Token Secret
-            #   env:
-            #       CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
-            #   run: |
-            #       kubectl create secret generic cloudflare-token-secret \
-            #         --from-literal=cloudflare-token=$CLOUDFLARE_TOKEN -n cert-manager
+            - name: Create cert-manager namespace
+              run: |
+                  kubectl create namespace cert-manager || echo "cert-manager namespace already exists"
+
+            - name: Create Cloudflare API Token Secret
+              env:
+                  CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
+              run: |
+
+                  kubectl create secret generic cloudflare-token-secret \
+                    --from-literal=cloudflare-token=$CLOUDFLARE_TOKEN -n cert-manager || echo "Cloudflare token secret already exists"
 
             - name: Install cloud-native operator
               run: |
@@ -554,7 +558,9 @@ jobs:
                     exit 1
                   fi
 
-                  # Actualizar la URL de retorno con la IP pública y el puerto correcto
+                  FRONTEND_SERVICE_IP=$(kubectl get svc frontend-service -n argocd -o=jsonpath='{.status.loadBalancer.ingress[0].ip}')
+
+                  NEW_CALLBACK_URL="http://$FRONTEND_SERVICE_IP"
                   NEW_CALLBACK_URL_HTTPS="https://frontend.leagueoftoken.online"
                   NEW_CALLBACK_URL_HTTP="http://frontend.leagueoftoken.online"
 
@@ -564,57 +570,72 @@ jobs:
                     --header "authorization: Bearer $ACCESS_TOKEN" \
                     --header 'content-type: application/json' \
                     --data '{
-                      "callbacks": ["http://localhost:5173", "http://127.0.0.1:5173", "'"$NEW_CALLBACK_URL_HTTPS"'", "'"$NEW_CALLBACK_URL_HTTP"'"],
-                      "allowed_logout_urls": ["http://localhost:5173", "http://127.0.0.1:5173", "'"$NEW_CALLBACK_URL_HTTPS"'", "'"$NEW_CALLBACK_URL_HTTP"'"],
-                      "web_origins": ["http://localhost:5173", "http://127.0.0.1:5173", "'"$NEW_CALLBACK_URL_HTTPS"'", "'"$NEW_CALLBACK_URL_HTTP"'"],
+                      "callbacks": ["http://localhost:5173", "http://127.0.0.1:5173", "'"$NEW_CALLBACK_URL_HTTPS"'", "'"$NEW_CALLBACK_URL_HTTP"'", "'"$NEW_CALLBACK_URL"'"],
+                      "allowed_logout_urls": ["http://localhost:5173", "http://127.0.0.1:5173", "'"$NEW_CALLBACK_URL_HTTPS"'", "'"$NEW_CALLBACK_URL_HTTP"'", "'"$NEW_CALLBACK_URL"'"],
+                      "web_origins": ["http://localhost:5173", "http://127.0.0.1:5173", "'"$NEW_CALLBACK_URL_HTTPS"'", "'"$NEW_CALLBACK_URL_HTTP"'", "'"$NEW_CALLBACK_URL"'"],
                     }' \
                     > /dev/null 2>&1
 
-            # TODO: Actualizar IPS en DNS tanto para backend como frontend
-            # - name: Update Cloudflare DNS
-            #   env:
-            #       CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
-            #       CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
-            #   run: |
-            #       # Fetch the external IP of the frontend LoadBalancer service
-            #       PUBLIC_IP=$(kubectl get svc frontend-service -n argocd -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
+            - name: Update Cloudflare DNS
+              env:
+                  CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
+                  CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
+              run: |
+                  # Fetch the external IP of the frontend LoadBalancer service
+                  FRONTEND_SERVICE_IP=$(kubectl get svc frontend-service -n argocd -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
+                  BACKEND_SERVICE_IP=$(kubectl get svc backend-service -n argocd -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
 
-            #       if [ -z "$PUBLIC_IP" ]; then
-            #           echo "Failed to fetch frontend IP"
-            #           exit 1
-            #       fi
+                  if [ -z "$FRONTEND_SERVICE_IP" ]; then
+                      echo "Failed to fetch frontend IP"
+                      exit 1
+                  fi
 
-            #       echo "getting RECORDS from Cloudflare"
-            #       # Fetch all A records from Cloudflare
-            #       RECORDS_JSON=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/dns_records?type=A" \
-            #         -H "Authorization: Bearer $CLOUDFLARE_TOKEN" \
-            #         -H "Content-Type: application/json")
+                  if [ -z "$BACKEND_SERVICE_IP" ]; then
+                      echo "Failed to fetch backend IP"
+                      exit 1
+                  fi
 
-            #       # Parse JSON to get individual records and update them with the new IP
-            #       echo "$RECORDS_JSON" | jq -c '.result[] | {id, name, content}' | while read -r record; do
-            #           RECORD_ID=$(echo $record | jq -r '.id')
-            #           RECORD_NAME=$(echo $record | jq -r '.name')
+                  get_dns_record_id() {
+                    local record_name="$1"
+                    local zone_id="$2"
+                    local token="$3"
 
-            #           echo "Updating DNS record $RECORD_NAME with IP $PUBLIC_IP"
+                    local api_url="https://api.cloudflare.com/client/v4/zones/$zone_id/dns_records?type=A&name=$record_name"
+                    local response=$(curl -s -X GET "$api_url" \
+                      -H "Authorization: Bearer $token" \
+                      -H "Content-Type: application/json")
 
-            #           # Update the DNS record
-            #           RESPONSE=$(curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/dns_records/$RECORD_ID" \
-            #             -H "Authorization: Bearer $CLOUDFLARE_TOKEN" \
-            #             -H "Content-Type: application/json" \
-            #             --data '{
-            #               "type": "A",
-            #               "name": "'"$RECORD_NAME"'",
-            #               "content": "'"$PUBLIC_IP"'",
-            #               "ttl": 1,
-            #               "proxied": false
-            #             }')
+                    local record_id=$(echo "$response" | jq -r '.result[0].id')
 
-            #           echo "Update response: $RESPONSE"
-            #           SUCCESS=$(echo $RESPONSE | jq -r '.success')
-            #           if [ "$SUCCESS" != "true" ]; then
-            #               echo "Failed to update DNS record $RECORD_NAME: $(echo $RESPONSE | jq -r '.errors[] .message')"
-            #           fi
-            #       done
+                    echo "$record_id"
+                  }
+
+                  # Obtener dinámicamente los IDs de los registros A
+                  BACKEND_DNS_RECORD_ID=$(get_dns_record_id "api.leagueoftoken.online" "$CLOUDFLARE_ZONE_ID" "$CLOUDFLARE_TOKEN")
+                  FRONTEND_DNS_RECORD_ID=$(get_dns_record_id "frontend.leagueoftoken.online" "$CLOUDFLARE_ZONE_ID" "$CLOUDFLARE_TOKEN")
+
+                  curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/dns_records/$FRONTEND_DNS_RECORD_ID" \
+                    -H "Authorization: Bearer $CLOUDFLARE_TOKEN" \
+                    -H "Content-Type: application/json" \
+                    --data '{
+                      "type": "A",
+                      "name": "frontend.leagueoftoken.online",
+                      "content": "'"$FRONTEND_SERVICE_IP"'",
+                      "ttl": 120,
+                      "proxied": true
+                    }'
+
+                  curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/dns_records/$BACKEND_DNS_RECORD_ID" \
+                    -H "Authorization: Bearer $CLOUDFLARE_TOKEN" \
+                    -H "Content-Type: application/json" \
+                    --data '{
+                      "type": "A",
+                      "name": "api.leagueoftoken.online",
+                      "content": "'"$BACKEND_SERVICE_IP"'",
+                      "ttl": 120,
+                      "proxied": true
+                    }'
+
             - name: Create Mercado Pago config
               env:
                   MP_ACCESS_TOKEN: ${{ secrets.MP_ACCESS_TOKEN }}
