update docker build

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -108,13 +108,21 @@ jobs:
                   AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
                   SPA_CLIENT_ID: ${{ secrets.AUTH0_SPA_CLIENT_ID }}
               run: |
-                  BACKEND_SERVICE_IP = $(kubectl get svc backend-service -n argocd -o=jsonpath='{.status.loadBalancer.ingress[0].ip}')
+                  # Obtener el servicio backend
+                  BACKEND_SERVICE=$(kubectl get svc backend-service -n argocd -o=jsonpath='{.status.loadBalancer.ingress[0].ip}')
 
-                  echo "APP_BACKEND_HOST=$BACKEND_SERVICE_IP" > frontend/.env.prod
-                  echo "APP_BACKEND_PORT=3000" > frontend/.env.prod
-                  echo "APP_AUTH0_AUDIENCE=$AUDIENCE" > frontend/.env.prod
-                  echo "APP_AUTH0_CLIENT_ID=$SPA_CLIENT_ID" > frontend/.env.prod
-                  echo "APP_AUTH0_DOMAIN=$AUTH0_DOMAIN" > frontend/.env.prod
+                  # Verificar si backend-service está vacío
+                  if [ -z "$BACKEND_SERVICE" ]; then
+                    echo "Error: backend-service is empty"
+                    exit 1
+                  fi
+
+                  # Escribir las variables de entorno en .env.prod
+                  echo "APP_BACKEND_HOST=$BACKEND_SERVICE" > frontend/.env.prod
+                  echo "APP_BACKEND_PORT=3000" >> frontend/.env.prod
+                  echo "APP_AUTH0_AUDIENCE=$AUDIENCE" >> frontend/.env.prod
+                  echo "APP_AUTH0_CLIENT_ID=$SPA_CLIENT_ID" >> frontend/.env.prod
+                  echo "APP_AUTH0_DOMAIN=$AUTH0_DOMAIN" >> frontend/.env.prod
 
             - name: Push frontend image
               uses: docker/build-push-action@v5
